[versions]
agp = "8.6.0"
kotlin = "2.0.21"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
androidxLifecycle = "2.8.4"
activityCompose = "1.9.1"
composeBom = "2025.05.01"
navigation-compose = "2.8.0-beta04"
dagger-hilt = "2.49"
androix-hilt= "1.2.0"
androix-hilt-viewmodel = "1.0.0-alpha03"
ksp = "2.0.21-1.0.27"
serialization = "1.7.3"
androidx-work = "2.9.1"
materialIconsExtended = "1.7.0-beta04"
uiTextGoogleFonts = "1.7.3"
room = "2.6.1"
bcrypt = "0.10.2"
security = "1.1.0-alpha06"
datastore = "1.1.1"
retrofit = "2.11.0"
okhttplogginginterceptor = "4.12.0"
coil = "3.0.0-rc01"
material3 = "1.5.0-alpha03"
reflect = "2.0.21"
shimmer = "1.3.1"
paging = "3.3.2"
palette = "1.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3"}

#compose lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle"}
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle"}
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle"}

androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlin-reflect = {group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflect"}


#Navigations
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger-hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androix-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androix-hilt" }

#Extended Icons
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
#Fonts downloadable
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }

#Room DB
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room"}

#Bcrpyt encryption
bcrypt = { group = "at.favre.lib", name = "bcrypt", version.ref = "bcrypt" }
androidx-security = { module = "androidx.security:security-crypto", version.ref = "security" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

#Retrofit
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit2-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
retrofit2-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit"}

#OKHTTP
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttplogginginterceptor"}

#Coil
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil"}
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil"}
coil-test = { module = "io.coil-kt.coil3:coil-test", version.ref = "coil"}

#Shimmer/Skeleton Loading
shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer" }

#Paging3
paging = {  group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
paging-compose = {   group = "androidx.paging", name = "paging-compose", version.ref = "paging" }

#Palette Builder
palette = {module = "androidx.palette:palette", version.ref = "palette"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

